services:
  mysql:
    image: mysql:5.6.41
    container_name: mysql
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - "./src/main/resources/db:/docker-entrypoint-initdb.d"
      - mysqldata:/var/lib/mysql
