version: '3'

services:
  mysql:
    image: mysql:5.6.41
    container_name: mysql
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_ECOMMERCE_DATABASE}
      MYSQL_USER: ${MYSQL_ECOMMERCE_USER}
      MYSQL_PASSWORD: ${MYSQL_ECOMMERCE_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - "./src/main/resources/db:/docker-entrypoint-initdb.d"
      - mysqldata:/var/lib/mysql
  ecommerce:
    container_name: ecommerce
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_ECOMMERCE_DATABASE: ${MYSQL_ECOMMERCE_DATABASE}
      MYSQL_ECOMMERCE_USER: ${MYSQL_ECOMMERCE_USER}
      MYSQL_ECOMMERCE_PASSWORD: ${MYSQL_ECOMMERCE_PASSWORD}
    ports:
      - "8080:8080"
volumes:
  mysqldata:
