/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.gbsfo.kafka.order;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum OrderStatus {
  CREATED, PROCESSING, SHIPPING, DELIVERED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"OrderStatus\",\"namespace\":\"com.gbsfo.kafka.order\",\"symbols\":[\"CREATED\",\"PROCESSING\",\"SHIPPING\",\"DELIVERED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
