/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.gbsfo.kafka.payment;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class PaymentCreated extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 644956646065137981L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PaymentCreated\",\"namespace\":\"com.gbsfo.kafka.payment\",\"fields\":[{\"name\":\"id\",\"type\":\"long\",\"doc\":\"Payment's ID\"},{\"name\":\"number\",\"type\":\"string\",\"doc\":\"Name\"},{\"name\":\"sum\",\"type\":{\"type\":\"bytes\",\"logicalType\":\"decimal\",\"precision\":10,\"scale\":2}},{\"name\":\"paymentDateTime\",\"type\":[\"null\",{\"type\":\"long\",\"logicalType\":\"timestamp\"}],\"doc\":\"Payment Date Time\",\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<PaymentCreated> ENCODER =
      new BinaryMessageEncoder<PaymentCreated>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<PaymentCreated> DECODER =
      new BinaryMessageDecoder<PaymentCreated>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<PaymentCreated> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<PaymentCreated> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<PaymentCreated>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this PaymentCreated to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a PaymentCreated from a ByteBuffer. */
  public static PaymentCreated fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Payment's ID */
  @Deprecated public long id;
  /** Name */
  @Deprecated public java.lang.CharSequence number;
  @Deprecated public java.nio.ByteBuffer sum;
  /** Payment Date Time */
  @Deprecated public java.lang.Long paymentDateTime;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PaymentCreated() {}

  /**
   * All-args constructor.
   * @param id Payment's ID
   * @param number Name
   * @param sum The new value for sum
   * @param paymentDateTime Payment Date Time
   */
  public PaymentCreated(java.lang.Long id, java.lang.CharSequence number, java.nio.ByteBuffer sum, java.lang.Long paymentDateTime) {
    this.id = id;
    this.number = number;
    this.sum = sum;
    this.paymentDateTime = paymentDateTime;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return number;
    case 2: return sum;
    case 3: return paymentDateTime;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  protected static final org.apache.avro.data.TimeConversions.DateConversion DATE_CONVERSION = new org.apache.avro.data.TimeConversions.DateConversion();
  protected static final org.apache.avro.data.TimeConversions.TimeConversion TIME_CONVERSION = new org.apache.avro.data.TimeConversions.TimeConversion();
  protected static final org.apache.avro.data.TimeConversions.TimestampConversion TIMESTAMP_CONVERSION = new org.apache.avro.data.TimeConversions.TimestampConversion();
  protected static final org.apache.avro.Conversions.DecimalConversion DECIMAL_CONVERSION = new org.apache.avro.Conversions.DecimalConversion();

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Long)value$; break;
    case 1: number = (java.lang.CharSequence)value$; break;
    case 2: sum = (java.nio.ByteBuffer)value$; break;
    case 3: paymentDateTime = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return Payment's ID
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * Payment's ID
   * @param value the value to set.
   */
  public void setId(java.lang.Long value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'number' field.
   * @return Name
   */
  public java.lang.CharSequence getNumber() {
    return number;
  }

  /**
   * Sets the value of the 'number' field.
   * Name
   * @param value the value to set.
   */
  public void setNumber(java.lang.CharSequence value) {
    this.number = value;
  }

  /**
   * Gets the value of the 'sum' field.
   * @return The value of the 'sum' field.
   */
  public java.nio.ByteBuffer getSum() {
    return sum;
  }

  /**
   * Sets the value of the 'sum' field.
   * @param value the value to set.
   */
  public void setSum(java.nio.ByteBuffer value) {
    this.sum = value;
  }

  /**
   * Gets the value of the 'paymentDateTime' field.
   * @return Payment Date Time
   */
  public java.lang.Long getPaymentDateTime() {
    return paymentDateTime;
  }

  /**
   * Sets the value of the 'paymentDateTime' field.
   * Payment Date Time
   * @param value the value to set.
   */
  public void setPaymentDateTime(java.lang.Long value) {
    this.paymentDateTime = value;
  }

  /**
   * Creates a new PaymentCreated RecordBuilder.
   * @return A new PaymentCreated RecordBuilder
   */
  public static com.gbsfo.kafka.payment.PaymentCreated.Builder newBuilder() {
    return new com.gbsfo.kafka.payment.PaymentCreated.Builder();
  }

  /**
   * Creates a new PaymentCreated RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PaymentCreated RecordBuilder
   */
  public static com.gbsfo.kafka.payment.PaymentCreated.Builder newBuilder(com.gbsfo.kafka.payment.PaymentCreated.Builder other) {
    return new com.gbsfo.kafka.payment.PaymentCreated.Builder(other);
  }

  /**
   * Creates a new PaymentCreated RecordBuilder by copying an existing PaymentCreated instance.
   * @param other The existing instance to copy.
   * @return A new PaymentCreated RecordBuilder
   */
  public static com.gbsfo.kafka.payment.PaymentCreated.Builder newBuilder(com.gbsfo.kafka.payment.PaymentCreated other) {
    return new com.gbsfo.kafka.payment.PaymentCreated.Builder(other);
  }

  /**
   * RecordBuilder for PaymentCreated instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PaymentCreated>
    implements org.apache.avro.data.RecordBuilder<PaymentCreated> {

    /** Payment's ID */
    private long id;
    /** Name */
    private java.lang.CharSequence number;
    private java.nio.ByteBuffer sum;
    /** Payment Date Time */
    private java.lang.Long paymentDateTime;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.gbsfo.kafka.payment.PaymentCreated.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.number)) {
        this.number = data().deepCopy(fields()[1].schema(), other.number);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.sum)) {
        this.sum = data().deepCopy(fields()[2].schema(), other.sum);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.paymentDateTime)) {
        this.paymentDateTime = data().deepCopy(fields()[3].schema(), other.paymentDateTime);
        fieldSetFlags()[3] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing PaymentCreated instance
     * @param other The existing instance to copy.
     */
    private Builder(com.gbsfo.kafka.payment.PaymentCreated other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.number)) {
        this.number = data().deepCopy(fields()[1].schema(), other.number);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.sum)) {
        this.sum = data().deepCopy(fields()[2].schema(), other.sum);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.paymentDateTime)) {
        this.paymentDateTime = data().deepCopy(fields()[3].schema(), other.paymentDateTime);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * Payment's ID
      * @return The value.
      */
    public java.lang.Long getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * Payment's ID
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.gbsfo.kafka.payment.PaymentCreated.Builder setId(long value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * Payment's ID
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * Payment's ID
      * @return This builder.
      */
    public com.gbsfo.kafka.payment.PaymentCreated.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'number' field.
      * Name
      * @return The value.
      */
    public java.lang.CharSequence getNumber() {
      return number;
    }

    /**
      * Sets the value of the 'number' field.
      * Name
      * @param value The value of 'number'.
      * @return This builder.
      */
    public com.gbsfo.kafka.payment.PaymentCreated.Builder setNumber(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.number = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'number' field has been set.
      * Name
      * @return True if the 'number' field has been set, false otherwise.
      */
    public boolean hasNumber() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'number' field.
      * Name
      * @return This builder.
      */
    public com.gbsfo.kafka.payment.PaymentCreated.Builder clearNumber() {
      number = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'sum' field.
      * @return The value.
      */
    public java.nio.ByteBuffer getSum() {
      return sum;
    }

    /**
      * Sets the value of the 'sum' field.
      * @param value The value of 'sum'.
      * @return This builder.
      */
    public com.gbsfo.kafka.payment.PaymentCreated.Builder setSum(java.nio.ByteBuffer value) {
      validate(fields()[2], value);
      this.sum = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'sum' field has been set.
      * @return True if the 'sum' field has been set, false otherwise.
      */
    public boolean hasSum() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'sum' field.
      * @return This builder.
      */
    public com.gbsfo.kafka.payment.PaymentCreated.Builder clearSum() {
      sum = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'paymentDateTime' field.
      * Payment Date Time
      * @return The value.
      */
    public java.lang.Long getPaymentDateTime() {
      return paymentDateTime;
    }

    /**
      * Sets the value of the 'paymentDateTime' field.
      * Payment Date Time
      * @param value The value of 'paymentDateTime'.
      * @return This builder.
      */
    public com.gbsfo.kafka.payment.PaymentCreated.Builder setPaymentDateTime(java.lang.Long value) {
      validate(fields()[3], value);
      this.paymentDateTime = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'paymentDateTime' field has been set.
      * Payment Date Time
      * @return True if the 'paymentDateTime' field has been set, false otherwise.
      */
    public boolean hasPaymentDateTime() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'paymentDateTime' field.
      * Payment Date Time
      * @return This builder.
      */
    public com.gbsfo.kafka.payment.PaymentCreated.Builder clearPaymentDateTime() {
      paymentDateTime = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public PaymentCreated build() {
      try {
        PaymentCreated record = new PaymentCreated();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Long) defaultValue(fields()[0], record.getConversion(0));
        record.number = fieldSetFlags()[1] ? this.number : (java.lang.CharSequence) defaultValue(fields()[1], record.getConversion(1));
        record.sum = fieldSetFlags()[2] ? this.sum : (java.nio.ByteBuffer) defaultValue(fields()[2], record.getConversion(2));
        record.paymentDateTime = fieldSetFlags()[3] ? this.paymentDateTime : (java.lang.Long) defaultValue(fields()[3], record.getConversion(3));
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<PaymentCreated>
    WRITER$ = (org.apache.avro.io.DatumWriter<PaymentCreated>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<PaymentCreated>
    READER$ = (org.apache.avro.io.DatumReader<PaymentCreated>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
