spring:
  profiles:
    active: dev
server:
  port: 8081
---
spring:
  config:
    activate:
      on-profile: dev
  kafka:
    topic:
      order: order-events
      item: item-events
      payment: payment-events
    consumer:
      bootstrap-servers:
        - localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id:
        - order-events-listener-group
        - item-events-listener-group
        - payment-events-listener-group
      auto-offset-reset: latest
    producer:
      bootstrap-servers:
        - localhost:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer